services:
  dataset_manager:
    build:
      context: .
      dockerfile: dataset_manager/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
  neural_net:
    build:
      context: .
      dockerfile: neural_net/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge